-- MySQL Script generated by MySQL Workbench
-- Sun Sep 10 23:20:28 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema appuaiinforma
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema appuaiinforma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `appuaiinforma` DEFAULT CHARACTER SET utf8 ;
USE `appuaiinforma` ;

-- -----------------------------------------------------
-- Table `appuaiinforma`.`unidadeDeAtentimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appuaiinforma`.`unidadeDeAtentimento` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(90) NULL,
  `Endereco` VARCHAR(90) NULL,
  `Bairro` VARCHAR(45) NULL,
  `Cidade` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  `Cep` VARCHAR(45) NULL,
  `Numero` INT NULL,
  `Tel` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appuaiinforma`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appuaiinforma`.`usuarios` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(95) NULL,
  `Email` VARCHAR(65) NULL,
  `Cemail` VARCHAR(65) NULL,
  `Senha` VARCHAR(45) NULL,
  `NivelPermissao` TINYINT(1) NULL,
  `unidadeDeAtentimento_Id` INT NOT NULL,
  `CreatedTime` DATETIME NULL,
  `UpdatedTime` DATETIME NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_usuarios_unidadeDeAtentimento1_idx` (`unidadeDeAtentimento_Id` ASC),
  CONSTRAINT `fk_usuarios_unidadeDeAtentimento1`
    FOREIGN KEY (`unidadeDeAtentimento_Id`)
    REFERENCES `appuaiinforma`.`unidadeDeAtentimento` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appuaiinforma`.`medicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appuaiinforma`.`medicos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(65) NULL,
  `CreatedTime` DATETIME NULL,
  `UpdatedTime` DATETIME NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appuaiinforma`.`especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appuaiinforma`.`especialidades` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(65) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appuaiinforma`.`setor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appuaiinforma`.`setor` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(65) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appuaiinforma`.`plantoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appuaiinforma`.`plantoes` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `medicos_Id` INT NOT NULL,
  `setor_Id` INT NOT NULL,
  `Data` DATE NULL,
  `HoraInicio` DATETIME NULL,
  `HoraFinal` DATETIME NULL,
  `unidadeDeAtentimento_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_plantoes_medicos_idx` (`medicos_Id` ASC),
  INDEX `fk_plantoes_setor1_idx` (`setor_Id` ASC),
  INDEX `fk_plantoes_unidadeDeAtentimento1_idx` (`unidadeDeAtentimento_Id` ASC),
  CONSTRAINT `fk_plantoes_medicos`
    FOREIGN KEY (`medicos_Id`)
    REFERENCES `appuaiinforma`.`medicos` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_plantoes_setor1`
    FOREIGN KEY (`setor_Id`)
    REFERENCES `appuaiinforma`.`setor` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_plantoes_unidadeDeAtentimento1`
    FOREIGN KEY (`unidadeDeAtentimento_Id`)
    REFERENCES `appuaiinforma`.`unidadeDeAtentimento` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appuaiinforma`.`medicos_tem_especionalidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appuaiinforma`.`medicos_tem_especionalidades` (
  `medicos_Id` INT NOT NULL,
  `especialidades_Id` INT NOT NULL,
  PRIMARY KEY (`medicos_Id`, `especialidades_Id`),
  INDEX `fk_medicos_has_escepialidades_escepialidades1_idx` (`especialidades_Id` ASC),
  INDEX `fk_medicos_has_escepialidades_medicos1_idx` (`medicos_Id` ASC),
  CONSTRAINT `fk_medicos_has_escepialidades_medicos1`
    FOREIGN KEY (`medicos_Id`)
    REFERENCES `appuaiinforma`.`medicos` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_medicos_has_escepialidades_escepialidades1`
    FOREIGN KEY (`especialidades_Id`)
    REFERENCES `appuaiinforma`.`especialidades` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appuaiinforma`.`sessoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `appuaiinforma`.`sessoes` (
  `Id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `Usuario` INT NOT NULL,
  `Ativo` TINYINT(1) NULL,
  `Token` VARCHAR(128) NULL,
  `CreatedTime` DATETIME NULL,
  `UpdateTime` DATETIME NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_sessoes_usuarios1_idx` (`Usuario` ASC),
  CONSTRAINT `fk_sessoes_usuarios1`
    FOREIGN KEY (`Usuario`)
    REFERENCES `appuaiinforma`.`usuarios` (`Id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
